import Link from 'next/link'
import { DashboardMockup, Card, Logo } from '../../components/Frame'

const services = [
 ['تطوير الأنظمة المؤسسية','أنظمة ERP وCRM ولوحات تحكم وبوابات رقمية وسير عمل مخصص للشركات والمؤسسات.','▣'],
 ['حلول الذكاء الاصطناعي','مساعدات ذكية، أتمتة عمليات، تحليل مستندات، دعم عملاء ذكي وتكاملات AI.','✦'],
 ['البنية التحتية السحابية','تصميم وترحيل وتشغيل بيئات سحابية آمنة مع مراقبة ونسخ احتياطي وخطط استمرارية.','☁'],
 ['تطبيقات الويب والموبايل','مواقع احترافية، منصات SaaS، تطبيقات جوال ولوحات إدارة متجاوبة وسريعة.','◈'],
 ['DevOps وتشغيل الأنظمة','CI/CD وDocker وKubernetes وLinux ومراقبة الإنتاج وأتمتة النشر.','⚙'],
 ['الأمن السيبراني','مراجعات أمنية، إدارة صلاحيات، تقوية الأنظمة، مراقبة واستعداد للحوادث.','◆']
]
const projects = ['منصة ERP مؤسسية','منصة دعم عملاء بالذكاء الاصطناعي','نظام إدارة مستشفيات','لوحة لوجستية ذكية','منظومة ترحيل سحابي','نظام إدارة تعليم إلكتروني']
const courses = ['تطوير Full Stack','Python والذكاء الاصطناعي','الحوسبة السحابية','DevOps','الأمن السيبراني','تطبيقات الموبايل']

export const metadata = { title: 'Novaris Technology | عربي' }

export default function Arabic(){return <><div className="bg"><span/><span/><span/></div><header className="nav"><div className="nav-inner"><Logo/><nav><Link href="/">English</Link><a href="#services">الخدمات</a><a href="#projects">المشاريع</a><a href="#training">التدريب</a></nav><Link className="btn small" href="/contact">ابدأ مشروعك</Link></div></header><main className="rtl"><section className="hero"><div className="mesh"/><div className="hero-content"><div className="pill">نوفاريس تكنولوجي</div><h1>نبني المستقبل بأنظمة ذكية وتقنيات فاخرة.</h1><p>Novaris Technology شركة تقنية متخصصة في تطوير الأنظمة المؤسسية، حلول الذكاء الاصطناعي، البنية التحتية السحابية، DevOps، الأمن السيبراني والتدريب التقني الاحترافي.</p><div className="hero-actions"><Link className="btn" href="#services">استكشف الخدمات</Link><Link className="btn ghost" href="#projects">شاهد المشاريع</Link></div></div><DashboardMockup/></section><section className="stats">{[['24/7','جاهزية للمراقبة'],['12+','مجال تقني'],['40+','تصميم حلول'],['99.9%','هدف اعتمادية']].map(([n,t])=><div className="stat" key={t}><b>{n}</b><span>{t}</span></div>)}</section><section id="services" className="section"><div className="section-title"><span className="eyebrow">خدماتنا</span><h2>حلول تقنية ذكية للشركات الحديثة.</h2><p>نجمع بين البرمجة الاحترافية، البنية السحابية، الذكاء الاصطناعي، الأمن والتدريب في تجربة واحدة متكاملة.</p></div><div className="grid cols-3">{services.map(([t,d,i])=><Card key={t}><div className="icon">{i}</div><h3>{t}</h3><p>{d}</p></Card>)}</div></section><section id="projects" className="section"><div className="section-title"><span className="eyebrow">أعمالنا</span><h2>نماذج مشاريع قوية تعكس قدراتنا التقنية.</h2><p>هذه نماذج حلول احترافية يمكن تنفيذها وتخصيصها حسب احتياجات الشركات والمؤسسات.</p></div><div className="grid cols-2">{projects.map(p=><Card key={p} className="project"><div><div className="visual"/><span className="eyebrow">دراسة حالة</span><h3>{p}</h3><p>تصميم حل تقني متكامل مع واجهات حديثة، صلاحيات، تقارير، تكاملات، أمان وبنية قابلة للتوسع.</p><div className="tags"><span className="tag">Next.js</span><span className="tag">Cloud</span><span className="tag">AI</span><span className="tag">Security</span></div></div></Card>)}</div></section><section id="training" className="section"><div className="section-title"><span className="eyebrow">الأكاديمية</span><h2>مسارات تدريب تقنية عملية.</h2></div><div className="grid cols-3">{courses.map(c=><Card key={c}><h3>{c}</h3><p>برنامج عملي مبني على مشاريع وتطبيقات حقيقية، مناسب للطلاب والخريجين والموظفين والفرق التقنية.</p></Card>)}</div></section></main><footer className="footer rtl"><div className="footer-cta"><div><span className="eyebrow">ابدأ الآن</span><h2>حوّل فكرتك إلى منصة رقمية فاخرة وقابلة للتوسع.</h2></div><Link className="btn" href="/contact">تواصل معنا</Link></div><div className="copyright">© 2026 Novaris Technology. جميع الحقوق محفوظة.</div></footer></>}
