export const services=[['AI Solutions','Intelligent assistants, automation workflows, RAG search, analytics and AI-enabled enterprise experiences.','✦'],['Enterprise Software','ERP, CRM, HR, finance, procurement and workflow platforms designed around business operations.','◈'],['Cloud Infrastructure','Secure cloud architecture, migration, monitoring, backups, Kubernetes and DevOps foundations.','☁'],['Cybersecurity','Identity, access controls, hardening, auditing, security monitoring and secure engineering practices.','◉'],['Web & Mobile Apps','Premium web platforms, dashboards, portals, e-commerce and mobile experiences for modern teams.','▣'],['Training Academy','Practical programming, AI, cloud, DevOps and cybersecurity learning paths for individuals and teams.','◎']]
export const projects=[
{slug:'enterprise-erp-suite',cat:'Enterprise Software',title:'Enterprise ERP Suite',desc:'A modular ERP platform for finance, HR, procurement, inventory, approvals and executive analytics.',tags:['ERP','Finance','HR','PostgreSQL']},
{slug:'ai-customer-support-platform',cat:'AI Automation',title:'AI Customer Support Platform',desc:'An AI helpdesk that answers questions, routes tickets and summarizes customer conversations.',tags:['LLM','RAG','Python','Automation']},
{slug:'hospital-management-system',cat:'Healthcare',title:'Hospital Management System',desc:'A healthcare platform for appointments, departments, billing, patient profiles and operational reports.',tags:['Healthcare','React','API','Security']},
{slug:'banking-analytics-suite',cat:'FinTech',title:'Banking Analytics Suite',desc:'Executive banking dashboard for transactions, risk signals, customer insights and reporting.',tags:['BI','Data','Cloud','Security']},
{slug:'smart-logistics-dashboard',cat:'Logistics',title:'Smart Logistics Dashboard',desc:'Fleet, warehouse and shipment visibility with KPI tracking, route intelligence and alerts.',tags:['Maps','Analytics','IoT','Cloud']},
{slug:'learning-management-platform',cat:'Education',title:'Learning Management Platform',desc:'A training portal for courses, lessons, exams, certificates and student progress tracking.',tags:['LMS','Video','Exams','Reports']}
]
export const programs=['Full Stack Web Development','Python for Automation & Data','AI Engineering & Prompt Systems','React & Next.js Professional','Flutter Mobile Development','Cloud Computing Foundations','Azure / AWS Deployment','DevOps with Docker & CI/CD','Cybersecurity Fundamentals','Business Analytics & Power BI']
export const arProjects=[
['منصة ERP مؤسسية','نظام متكامل لإدارة المالية والموارد البشرية والمشتريات والمخزون والموافقات والتقارير التنفيذية.'],['منصة دعم عملاء بالذكاء الاصطناعي','مساعد ذكي للرد على العملاء وتوجيه التذاكر وتلخيص المحادثات وتخفيف ضغط فرق الدعم.'],['نظام إدارة مستشفيات','منصة لإدارة المواعيد والأقسام والفواتير وملفات المرضى والتقارير التشغيلية.'],['لوحة تحليلات مصرفية','منصة مؤشرات تنفيذية للمعاملات والمخاطر وسلوك العملاء والتقارير المالية.']]
