import Link from 'next/link';
import {projects,services,courses,industries,process} from '../lib/data';

function Nav(){return <header className="nav"><div className="navin"><Link href="/" className="brand"><div className="logo">N</div><div><h1>Novaris Technology</h1><p>AI, Cloud & Enterprise Software</p></div></Link><nav className="links"><a href="#services">Services</a><a href="#projects">Projects</a><a href="#training">Training</a><Link href="/about">About</Link><Link href="/ar">العربية</Link><Link className="btn" href="/start-project">Start a Project →</Link></nav></div></header>}
function Metric({value,label}){return <div className="metric"><b>{value}</b><p>{label}</p></div>}
function ProjectCard({p}){return <article className="case"><Link href={`/projects/${p.slug}`} className="shot"><img src={p.image} alt={p.title}/><span className="view">Open Case Study →</span></Link><div className="casebody"><span className="tag">{p.category}</span><h3>{p.title}</h3><p className="muted">{p.summary}</p><div className="chips">{p.tags.slice(0,5).map(t=><span className="chip" key={t}>{t}</span>)}</div><Link className="caseLink" href={`/projects/${p.slug}`}>View Case Study →</Link></div></article>}
function ServiceCard({s,i}){return <div className="service"><div className="serviceIcon">{String(i+1).padStart(2,'0')}</div><h3>{s.title}</h3><p>{s.text}</p><div className="chips">{s.stack.map(x=><span className="chip" key={x}>{x}</span>)}</div></div>}

const academyPrograms = [
 {title:'Full Stack Web Development', label:'Software Engineering', visual:'Code + browser + API', duration:'16 weeks', level:'Beginner → Advanced', desc:'Build production web applications with React, Next.js, Node.js, authentication, REST APIs and PostgreSQL.', tools:['React','Next.js','Node.js','PostgreSQL']},
 {title:'AI Engineering & Prompt Systems', label:'AI Professional', visual:'AI agent + RAG pipeline', duration:'14 weeks', level:'Advanced', desc:'Design AI assistants, prompt systems, vector search, RAG workflows and enterprise LLM applications.', tools:['LLM','RAG','Python','Vector DB']},
 {title:'Cloud & DevOps Engineering', label:'Cloud Infrastructure', visual:'CI/CD + Kubernetes', duration:'12 weeks', level:'Intermediate → Advanced', desc:'Deploy secure cloud systems with Docker, Kubernetes, GitHub Actions, monitoring and infrastructure automation.', tools:['Azure','AWS','Docker','K8s']},
 {title:'Flutter Mobile Development', label:'Mobile Product', visual:'iOS + Android app screens', duration:'14 weeks', level:'Intermediate', desc:'Create cross-platform mobile apps with Firebase, APIs, authentication, notifications and release workflows.', tools:['Flutter','Firebase','REST API','Mobile UI']},
 {title:'Cybersecurity Fundamentals', label:'Security Operations', visual:'SOC + threat dashboard', duration:'12 weeks', level:'Intermediate', desc:'Learn secure infrastructure, OWASP, IAM, vulnerability assessment, SIEM workflows and security reporting.', tools:['SOC','IAM','OWASP','SIEM']},
 {title:'Business Analytics & Power BI', label:'Data Intelligence', visual:'Executive BI dashboard', duration:'8 weeks', level:'Beginner → Intermediate', desc:'Turn raw data into KPI dashboards, executive reports, analytics models and decision-ready insights.', tools:['Power BI','SQL','KPIs','Reports']}
];
function TrainingPreviewCard({c,i}){return <article className={`academyPreviewCard ap${i}`}><div className="academyPreviewVisual"><div className="apTop"><span></span><span></span><span></span><b>{c.visual}</b></div><div className="apCanvas"><i></i><i></i><i></i><i></i></div></div><div className="programHead"><span className="tag">{c.label}</span><b>{c.duration}</b></div><h3>{c.title}</h3><p className="muted">{c.desc}</p><div className="programMeta"><span>{c.level}</span><span>Certificate</span><span>Capstone</span></div><div className="chips">{c.tools.map(t=><span className="chip" key={t}>{t}</span>)}</div><Link className="caseLink" href="/training#programs">View Curriculum →</Link></article>}

export default function Home(){return <main className="site gridbg"><Nav/>
<section className="container hero">
  <div className="hero-copy"><span className="pill">AI-POWERED • CLOUD-READY • ENTERPRISE-GRADE</span><h2>Engineering digital <span className="grad">platforms</span> that look premium and perform at scale.</h2><p className="lead">Novaris Technology designs enterprise software, AI automation and cloud infrastructure for organizations that need secure, elegant and measurable digital systems.</p><div className="actions"><Link className="btn" href="/start-project">Start Your Project →</Link><a className="ghost" href="#projects">Explore Projects</a></div><div className="hero-metrics"><Metric value="50+" label="Project showpieces"/><Metric value="12" label="Solution domains"/><Metric value="99.9%" label="Target cloud uptime"/><Metric value="24/7" label="Monitoring mindset"/></div></div>
  <div className="hero-visual"><img src="/images/hero-dashboard.png" alt="Novaris premium dashboard preview"/></div>
</section>

<section className="container section logoStrip"><span>React</span><span>Next.js</span><span>Python</span><span>Docker</span><span>Kubernetes</span><span>Azure</span><span>AWS</span><span>PostgreSQL</span><span>OpenAI APIs</span></section>

<section id="projects" className="container section projects-section"><div className="section-head"><div><span className="eyebrow">FEATURED CASE STUDIES</span><h2>Project visuals that look like <span className="grad">real products</span>, not empty placeholders.</h2><p className="muted wide">Each project includes its own interface style: ERP operations, AI helpdesk, banking analytics, hospital workflows, logistics maps, LMS portals and commerce intelligence.</p></div><Link className="ghost" href="/projects/enterprise-erp-suite">View Case Study →</Link></div><div className="projects">{projects.map(p=><ProjectCard p={p} key={p.slug}/>)}</div></section>

<section id="services" className="container section"><span className="eyebrow">SERVICES</span><h2>Services for companies that need serious technology.</h2><p className="muted wide">From discovery to deployment, Novaris combines product design, software engineering, AI and cloud infrastructure into one delivery model.</p><div className="services">{services.map((s,i)=><ServiceCard s={s} i={i} key={s.title}/>)}</div></section>

<section className="container section split"><div><span className="eyebrow">INDUSTRIES</span><h2>Built for complex business environments.</h2><p className="muted wide">We structure solutions around real operational needs across healthcare, finance, education, logistics, government services, retail and enterprise operations.</p></div><div className="industryGrid">{industries.map(x=><div className="industry" key={x}>{x}</div>)}</div></section>

<section id="training" className="container section academyPreviewSection"><div className="section-head"><div><span className="eyebrow">NOVARIS ACADEMY</span><h2>Specialized programs with real outcomes, different stacks and project-based delivery.</h2><p className="muted wide">Each training path is designed as a practical product-building journey with its own curriculum, tools, capstone project and career direction.</p></div><Link className="btn" href="/training#programs">Explore Programs →</Link></div><div className="academyPreviewGrid">{academyPrograms.map((c,i)=><TrainingPreviewCard c={c} i={i} key={c.title}/>)}</div></section>

<section className="container section"><div className="section-head"><div><span className="eyebrow">PROCESS</span><h2>From idea to production-ready system.</h2></div></div><div className="process">{process.map((p,i)=><div className="step" key={p.title}><span>{String(i+1).padStart(2,'0')}</span><h3>{p.title}</h3><p className="muted">{p.text}</p></div>)}</div></section>

<section className="container section"><div className="finalcta"><span className="pill">Ready to build?</span><h2>Start with a clear plan, then build the right system.</h2><p className="muted">Tell us what you want to build and we will prepare a structured project direction.</p><Link className="btn" href="/start-project">Start a Project →</Link></div></section><footer className="footer">© 2026 Novaris Technology. Enterprise software, AI, cloud and training.</footer></main>}
