import Link from 'next/link'
import { ArrowRight, Sparkles, ShieldCheck, Cpu, Cloud, Code2, GraduationCap, BarChart3, LockKeyhole, Zap } from 'lucide-react'
import { services, projects, courses, testimonials } from './data'

export function Header(){return <header className="nav"><Link className="brand" href="/"><span className="logo">N</span><span>Novaris <b>Technology</b></span></Link><nav><Link href="/services">Services</Link><Link href="/solutions">Solutions</Link><Link href="/projects">Projects</Link><Link href="/training">Training</Link><Link href="/about">About</Link><Link href="/contact">Contact</Link></nav><Link className="navCta" href="/contact">Start a Project <ArrowRight size={16}/></Link></header>}
export function Footer(){return <footer className="footer"><div className="footerGlow"/><div><Link className="brand" href="/"><span className="logo">N</span><span>Novaris <b>Technology</b></span></Link><p>Enterprise software, AI, cloud infrastructure, training, and digital platforms engineered for serious organizations.</p></div><div className="footGrid"><div><b>Company</b><Link href="/about">About</Link><Link href="/projects">Projects</Link><Link href="/contact">Contact</Link></div><div><b>Solutions</b><Link href="/services">Services</Link><Link href="/solutions">AI & Cloud</Link><Link href="/training">Training</Link></div><div><b>Legal</b><Link href="/privacy">Privacy</Link><Link href="/terms">Terms</Link><Link href="/acceptable-use">Acceptable Use</Link></div></div><small>© 2026 Novaris Technology. All rights reserved.</small></footer>}
export function Shell({children}){return <><div className="cursorGlow"/><div className="mesh"/><Header/>{children}<Footer/></>}
export function Hero(){return <section className="hero"><div className="particles"/><div className="heroText"><span className="eyebrow"><Sparkles size={14}/> AI • Cloud • Enterprise Software</span><h1>Engineering the Future with <span>Intelligent Technology.</span></h1><p>Novaris Technology designs, develops, and deploys secure enterprise software, cloud infrastructure, AI automation, and high-performance digital platforms that drive measurable business impact.</p><div className="actions"><Link className="primary" href="/contact">Start Your Project <ArrowRight size={18}/></Link><Link className="secondary" href="/projects">View Portfolio</Link></div></div><DashboardMockup/></section>}
export function DashboardMockup(){return <div className="mockWrap"><div className="orb orb1"/><div className="orb orb2"/><div className="platform"><div className="mockup"><div className="mockTop"><span/> <b>Novaris Operations Cloud</b><em>Live</em></div><div className="statRow"><div><small>Revenue Protected</small><strong>$98,764.21</strong></div><div><small>Cloud Uptime</small><strong>99.99%</strong></div><div><small>AI Models</small><strong>18</strong></div></div><div className="chart"><i/><i/><i/><i/><i/><i/></div><div className="miniGrid"><span>Security ✓</span><span>Deployments 24</span><span>Latency 18ms</span><span>AI Routing Active</span></div></div><div className="phone"><b>AI Analytics</b><div className="pulse"/><span>Operational</span></div></div></div>}
export function Stats(){return <section className="stats"><div><strong>150+</strong><span>Projects Delivered</span></div><div><strong>40+</strong><span>Enterprise Clients</span></div><div><strong>12</strong><span>Countries Supported</span></div><div><strong>24/7</strong><span>Monitoring & Support</span></div></section>}
function iconFor(i){return [Cpu,Cloud,Code2,LockKeyhole,Zap,GraduationCap][i%6]}
export function ServicesPreview(){return <section className="section"><div className="sectionHead"><span>What we do</span><h2>Intelligent solutions for modern businesses.</h2><p>From AI automation to cloud engineering and enterprise platforms, Novaris builds technology that scales.</p></div><div className="cards">{services.map((s,i)=>{const Icon=iconFor(i);return <Link href={s[2]} className="card tilt" key={s[0]}><Icon size={34}/><h3>{s[0]}</h3><p>{s[1]}</p><em>Explore <ArrowRight size={14}/></em></Link>})}</div></section>}
export function ProjectsPreview(){return <section className="section projects"><div className="sectionHead"><span>Our work</span><h2>Digital experiences. Real results.</h2><p>Featured concepts and case-study style examples demonstrating the type of systems Novaris can build.</p></div><div className="featureProject"><div><span className="badge">Featured Project</span><h3>{projects[0].title}</h3><p>{projects[0].desc}</p><div className="chips">{projects[0].stack.map(x=><span key={x}>{x}</span>)}</div><Link className="primary small" href="/projects">View Case Studies</Link></div><div className="videoCard"><div className="play">▶</div></div></div><div className="projectRail">{projects.slice(1).map(p=><Link className="projectMini" href="/projects" key={p.title}><span>{p.tag}</span><h4>{p.title}</h4><p>{p.metric}</p></Link>)}</div></section>}
export function Training(){return <section className="section"><div className="sectionHead"><span>Academy</span><h2>Professional training paths.</h2><p>Practical courses designed for developers, IT teams, and cloud professionals who want real market skills.</p></div><div className="courseGrid">{courses.map(c=><div className="course" key={c[0]}><GraduationCap/><h3>{c[0]}</h3><p>{c[1]}</p></div>)}</div></section>}
export function Testimonials(){return <section className="section"><div className="sectionHead"><span>Trust</span><h2>Built for serious teams.</h2></div><div className="quotes">{testimonials.map(t=><blockquote key={t[1]}><p>“{t[0]}”</p><cite>{t[1]}</cite></blockquote>)}</div></section>}
export function CTA(){return <section className="cta"><div><h2>Ready to build something extraordinary?</h2><p>Tell us about your idea, platform, automation, or cloud environment. We will help you turn it into a polished digital product.</p><Link className="primary" href="/contact">Start a Project <ArrowRight size={18}/></Link></div><div className="bigN">N</div></section>}
export function PageHero({title,subtitle}){return <section className="pageHero"><span className="eyebrow"><Sparkles size={14}/> Novaris Technology</span><h1>{title}</h1><p>{subtitle}</p></section>}
