export const projects = [
 {slug:'enterprise-erp-suite', title:'Enterprise ERP Suite', category:'Enterprise Software', image:'/images/erp.png', tags:['Next.js','PostgreSQL','Docker','AWS','RBAC'], summary:'A modular ERP platform for finance, HR, procurement, inventory, approvals and executive analytics.', challenge:'Disconnected spreadsheets and manual approvals slowed financial, HR and inventory operations.', solution:'Novaris designed a unified ERP workspace with role-based dashboards, automated approvals, audit trails and real-time reporting.', results:['42% faster approval cycles','Single source of truth for operations','Executive dashboards for finance and procurement']},
 {slug:'ai-customer-support-platform', title:'AI Customer Support Platform', category:'AI Solutions', image:'/images/ai-helpdesk.png', tags:['Python','RAG','LLM','Redis','Agents'], summary:'An AI helpdesk that answers questions, routes tickets and summarizes customer conversations.', challenge:'Support teams were overwhelmed by repeated questions and fragmented ticket history.', solution:'We designed an AI assistant with knowledge retrieval, smart routing, escalation logic and conversation summaries.', results:['70% automated first responses','Faster ticket triage','Consistent multilingual support experience']},
 {slug:'banking-analytics-suite', title:'Banking Analytics Suite', category:'FinTech', image:'/images/banking.png', tags:['React','BI','Security','Cloud','Fraud'], summary:'Real-time analytics platform for transactions, risk signals, customer insights and reporting.', challenge:'Executives needed secure visibility across transaction trends, risk patterns and digital adoption.', solution:'Novaris designed a secure analytics suite with KPI cards, fraud indicators, transaction charts and role-based dashboards.', results:['Real-time transaction visibility','Risk patterns surfaced earlier','Board-ready executive reports']},
 {slug:'hospital-management-system', title:'Hospital Management System', category:'Healthcare', image:'/images/hospital.png', tags:['Next.js','React','API','Security','FHIR'], summary:'A healthcare platform for appointments, departments, billing, patient profiles and operational reports.', challenge:'Patient flow, appointments and billing were managed across disconnected systems.', solution:'We created a unified hospital workspace with department views, appointment scheduling, billing and clinical reporting.', results:['Improved appointment visibility','Better patient record access','Operational reporting for management']},
 {slug:'smart-logistics-dashboard', title:'Smart Logistics Dashboard', category:'Logistics', image:'/images/logistics.png', tags:['Maps','Analytics','IoT','Cloud','Alerts'], summary:'Fleet, warehouse and shipment visibility with KPI tracking, route intelligence and alerts.', challenge:'Logistics teams lacked live visibility into routes, deliveries and warehouse operations.', solution:'Novaris built a command dashboard combining route maps, delivery KPIs, fleet health and operational alerts.', results:['Live route monitoring','Delivery performance tracking','Warehouse and fleet visibility']},
 {slug:'learning-management-platform', title:'Learning Management Platform', category:'Education', image:'/images/lms.png', tags:['LMS','Video','Exams','Reports','Certificates'], summary:'A training portal for courses, lessons, exams, certificates and student progress tracking.', challenge:'Training providers needed a polished learning portal with progress, certificates and content management.', solution:'We designed an LMS with course catalogs, student dashboards, exams, certificates and instructor analytics.', results:['Structured learning paths','Progress dashboards','Certificate-ready training programs']},
 {slug:'government-service-portal', title:'Government Service Portal', category:'Government', image:'/images/government.png', tags:['Portal','Workflow','Security','Reports','Forms'], summary:'A citizen-service platform for digital applications, approvals, document tracking and reports.', challenge:'Manual public-service workflows created delays and poor visibility for applicants and managers.', solution:'Novaris designed a service portal with application tracking, approval queues, status updates and dashboards.', results:['Clear digital application flow','Reduced manual follow-up','Transparent service status tracking']},
 {slug:'ecommerce-analytics-suite', title:'E-commerce Analytics Suite', category:'Retail', image:'/images/ecommerce.png', tags:['Commerce','Orders','Analytics','Cloud','CRM'], summary:'Commerce intelligence for orders, revenue, inventory, customers and product performance.', challenge:'Retail teams needed one place to understand sales, inventory and customer behavior.', solution:'We built a modern commerce analytics dashboard with revenue trends, orders, products and customer segments.', results:['Better inventory decisions','Revenue and product performance insight','Customer behavior visibility']}
];
export const services = [
 {title:'Enterprise Software',text:'ERP, CRM, HR, finance, procurement and internal workflow platforms designed for scale.',stack:['ERP','CRM','Dashboards']},
 {title:'AI Automation',text:'AI assistants, RAG search, document processing, ticket routing and business process automation.',stack:['LLM','RAG','Agents']},
 {title:'Cloud Infrastructure',text:'Secure deployment architectures, monitoring, backup strategy and cloud migration roadmaps.',stack:['Azure','AWS','Docker']},
 {title:'Web Platforms',text:'High-performance websites, SaaS portals, admin panels and customer-facing applications.',stack:['Next.js','React','API']},
 {title:'Mobile Applications',text:'Mobile experiences for operations, customers, training and field teams.',stack:['Flutter','iOS','Android']},
 {title:'DevOps & CI/CD',text:'Automated delivery pipelines, containers, observability and release workflows.',stack:['CI/CD','K8s','Monitoring']},
 {title:'Cybersecurity',text:'Secure application architecture, IAM, audit trails, vulnerability review and hardening.',stack:['IAM','Audit','SOC']},
 {title:'UI/UX Design',text:'Premium interfaces, product flows, design systems and dashboard experiences.',stack:['Design','UX','Systems']},
 {title:'Data Analytics',text:'Business intelligence, reporting, KPI dashboards and operational analytics.',stack:['BI','ETL','Reports']},
 {title:'Professional Training',text:'Practical technology courses for developers, teams and enterprise departments.',stack:['Academy','Labs','Certs']}
];
export const courses = ['Full Stack Web Development','Python Automation & Data','AI Engineering & Prompt Systems','React & Next.js Professional','Flutter Mobile Development','Cloud Computing Foundations','Azure / AWS Deployment','DevOps with Docker & CI/CD','Cybersecurity Fundamentals','Business Analytics & Power BI'];
export const industries = ['Healthcare','Finance','Education','Government','Retail','Logistics','Manufacturing','Hospitality','Startups','Enterprise Teams'];
export const process = [
 {title:'Discovery',text:'Clarify the business goal, workflows, users, risks and success metrics.'},
 {title:'Architecture',text:'Plan the data model, infrastructure, security, integrations and delivery roadmap.'},
 {title:'Design & Build',text:'Create polished interfaces and develop clean, scalable application modules.'},
 {title:'Launch & Improve',text:'Deploy, monitor, collect feedback and iterate with measurable improvements.'}
];
