export const projects = [
 {slug:'enterprise-erp-suite', title:'Enterprise ERP Suite', category:'Enterprise Software', image:'/images/erp.png', tags:['Next.js','PostgreSQL','Docker','AWS'], summary:'A modular ERP platform for finance, HR, procurement, inventory, approvals and executive analytics.', challenge:'Disconnected spreadsheets and manual approvals slowed financial, HR and inventory operations.', solution:'Novaris designed a unified ERP workspace with role-based dashboards, automated approvals, audit trails and real-time reporting.', results:['42% faster approval cycles','Single source of truth for operations','Executive dashboards for finance and procurement']},
 {slug:'ai-customer-support-platform', title:'AI Customer Support Platform', category:'AI Solutions', image:'/images/ai-helpdesk.png', tags:['Python','RAG','LLM','Redis'], summary:'An AI helpdesk that answers questions, routes tickets and summarizes customer conversations.', challenge:'Support teams were overwhelmed by repeated questions and fragmented ticket history.', solution:'We designed an AI assistant with knowledge retrieval, smart routing, escalation logic and conversation summaries.', results:['70% automated first responses','Faster ticket triage','Consistent multilingual support experience']},
 {slug:'banking-analytics-suite', title:'Banking Analytics Suite', category:'FinTech', image:'/images/banking.png', tags:['React','BI','Security','Cloud'], summary:'Real-time analytics platform for transactions, risk signals, customer insights and reporting.', challenge:'Executives needed secure visibility across transaction trends, risk patterns and digital adoption.', solution:'Novaris designed a secure analytics suite with KPI cards, fraud indicators, transaction charts and role-based dashboards.', results:['Real-time transaction visibility','Risk patterns surfaced earlier','Board-ready executive reports']},
 {slug:'hospital-management-system', title:'Hospital Management System', category:'Healthcare', image:'/images/hospital.png', tags:['Next.js','React','API','Security'], summary:'A healthcare platform for appointments, departments, billing, patient profiles and operational reports.', challenge:'Patient flow, appointments and billing were managed across disconnected systems.', solution:'We created a unified hospital workspace with department views, appointment scheduling, billing and clinical reporting.', results:['Improved appointment visibility','Better patient record access','Operational reporting for management']},
 {slug:'smart-logistics-dashboard', title:'Smart Logistics Dashboard', category:'Logistics', image:'/images/logistics.png', tags:['Maps','Analytics','IoT','Cloud'], summary:'Fleet, warehouse and shipment visibility with KPI tracking, route intelligence and alerts.', challenge:'Logistics teams lacked live visibility into routes, deliveries and warehouse operations.', solution:'Novaris built a command dashboard combining route maps, delivery KPIs, fleet health and operational alerts.', results:['Live route monitoring','Delivery performance tracking','Warehouse and fleet visibility']},
 {slug:'learning-management-platform', title:'Learning Management Platform', category:'Education', image:'/images/lms.png', tags:['LMS','Video','Exams','Reports'], summary:'A training portal for courses, lessons, exams, certificates and student progress tracking.', challenge:'Training providers needed a polished learning portal with progress, certificates and content management.', solution:'We designed an LMS with course catalogs, student dashboards, exams, certificates and instructor analytics.', results:['Structured learning paths','Progress dashboards','Certificate-ready training programs']},
 {slug:'government-service-portal', title:'Government Service Portal', category:'Government', image:'/images/government.png', tags:['Portal','Workflow','Security','Reports'], summary:'A citizen-service platform for digital applications, approvals, document tracking and reports.', challenge:'Manual public-service workflows created delays and poor visibility for applicants and managers.', solution:'Novaris designed a service portal with application tracking, approval queues, status updates and dashboards.', results:['Clear digital application flow','Reduced manual follow-up','Transparent service status tracking']},
 {slug:'ecommerce-analytics-suite', title:'E-commerce Analytics Suite', category:'Retail', image:'/images/ecommerce.png', tags:['Commerce','Orders','Analytics','Cloud'], summary:'Commerce intelligence for orders, revenue, inventory, customers and product performance.', challenge:'Retail teams needed one place to understand sales, inventory and customer behavior.', solution:'We built a modern commerce analytics dashboard with revenue trends, orders, products and customer segments.', results:['Better inventory decisions','Revenue and product performance insight','Customer behavior visibility']}
];
export const services = ['Enterprise Software','AI Automation','Cloud Infrastructure','Web Platforms','Mobile Applications','DevOps & CI/CD','Cybersecurity','UI/UX Design','Data Analytics','Professional Training'];
export const courses = ['Full Stack Web Development','Python Automation & Data','AI Engineering & Prompt Systems','React & Next.js Professional','Flutter Mobile Development','Cloud Computing Foundations','Azure / AWS Deployment','DevOps with Docker & CI/CD','Cybersecurity Fundamentals','Business Analytics & Power BI'];
